import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/chunks/layoutChunks/header";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import { SignIn } from "@/components/chunks/notSignedIn/signIn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
            <SignIn>
              <SignInButton />
            </SignIn>
          </SignedOut>
          <SignedIn>
            <Header />
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
